name: Java CI

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  publish-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew build
